name: base
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.11.6
  - matplotlib-base=3.8.2=py311h54ef318_0
  - numpy=1.26.2=py311h64a7726_0
  - scikit-image=0.22.0=py311h320fe9a_2
  - scikit-learn=1.3.2=py311hc009520_1
  - scipy=1.11.4=py311h64a7726_0
  - pandas==1.5.3
  - xarray==2024.2.0
  - tqdm=4.66.1=pyhd8ed1ab_0
  - rdkit=2023.09.5=py311h4c2f14b_0
  - ipywidgets=8.1.1=pyhd8ed1ab_0
  - jupyterlab=4.0.9=pyhd8ed1ab_0
  - voila==0.5.5
  - ipympl=0.9.3=pyhd8ed1ab_0




